### ISSUE TITLE
Email indicata non esistente

### ISSUE THREAD

**Issue by tmontanaro** [SoNet-2017/NewSocial#3]
Ho provato ad inviarvi un'email con un tutorial per implementare una video chat in AngularJS ed ho scoperto che una delle email che avete inserito sul vostro sito non esiste:
michele.drago@studenti.polito.it

**Comment by MicheleDrago** [comment]
problema risolto, dovevo attivare l'alias su sito della didattica

**Comment by tmontanaro** [comment]
Ok, perfetto!!! ;-)
